maps:
  map1:
    rows: 10
    cols: 10
    data: [0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
           0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 
           0, 0, 1, 0, 0, 0, 0, 1, 1, 1,
           0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
           0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
           0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
           0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
           0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
           0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
           0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
  map2:
    rows: 10
    cols: 10
    data: [0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
           0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 
           0, 0, 1, 0, 1, 1, 0, 1, 1, 1,
           0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
           0, 0, 1, 1, 1, 0, 0, 1, 0, 0,
           0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
           0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
           0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
           0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
           0, 0, 1, 0, 1, 0, 0, 0, 0, 0]
  map3:
    rows: 10
    cols: 10
    data: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
           0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
           0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
           0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
           0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
           0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
           0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
           0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
           0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
           0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
  map4:
    rows: 10
    cols: 10
    data: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
           0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 
           0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
           0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
           0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
           0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
           0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
           0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
           0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
           0, 1, 0, 0, 0, 0, 0, 0, 0, 0]
  map5:
    rows: 10
    cols: 10
    data: [0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
           0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 
           0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
           0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
           0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
           0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
           0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
           0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
           0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
           0, 1, 0, 0, 0, 0, 0, 0, 0, 0]
